[package]
name = "ortho-games/orthoutil"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"
authors = ["DylWithlt, RoboGojo"]

description = "An Ortho Games utility library for easy access general purpose functions."

realm = "shared"

exclude = ["README.md"]

[dependencies]
